import { Badge } from "@/components/ui/badge";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

const logs = [
  {
    recipient: "09171234567",
    type: "Queue Almost Ready",
    status: "Sent",
    office: "Registrar",
    time: "10:12 AM",
  },
  {
    recipient: "09181234567",
    type: "Now Serving",
    status: "Sent",
    office: "Cashier",
    time: "10:18 AM",
  },
  {
    recipient: "09192345678",
    type: "Missed Queue",
    status: "Failed",
    office: "Admission",
    time: "10:25 AM",
  },
  {
    recipient: "09193456789",
    type: "Queue Almost Ready",
    status: "Pending",
    office: "Registrar",
    time: "10:31 AM",
  },
];

function badgeVariant(status: string) {
  switch (status) {
    case "Sent":
      return "default";

    case "Pending":
      return "secondary";

    case "Failed":
      return "destructive";

    default:
      return "outline";
  }
}

export default function SmsLogsTable() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Recent SMS Logs</CardTitle>

        <CardDescription>
          Recent SMS notifications generated by the system.
        </CardDescription>
      </CardHeader>

      <CardContent>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Recipient</TableHead>
              <TableHead>Message Type</TableHead>
              <TableHead>Office</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Time</TableHead>
            </TableRow>
          </TableHeader>

          <TableBody>
            {logs.map((log, index) => (
              <TableRow key={index}>
                <TableCell className="font-medium">
                  {log.recipient}
                </TableCell>

                <TableCell>{log.type}</TableCell>

                <TableCell>{log.office}</TableCell>

                <TableCell>
                  <Badge variant={badgeVariant(log.status)}>
                    {log.status}
                  </Badge>
                </TableCell>

                <TableCell>{log.time}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}