import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

import {
  Eye,
  Download,
} from "lucide-react";

const reports = [
  {
    id: "REP-001",
    name: "Daily Queue Report",
    type: "Queue",
    generatedBy: "Admin",
    date: "Aug 05, 2026",
    status: "Ready",
  },
  {
    id: "REP-002",
    name: "Weekly Analytics Report",
    type: "Analytics",
    generatedBy: "Admin",
    date: "Aug 04, 2026",
    status: "Ready",
  },
  {
    id: "REP-003",
    name: "Monthly Forecast Report",
    type: "Forecast",
    generatedBy: "Admin",
    date: "Aug 01, 2026",
    status: "Ready",
  },
  {
    id: "REP-004",
    name: "Service Performance Report",
    type: "Performance",
    generatedBy: "Admin",
    date: "Jul 31, 2026",
    status: "Processing",
  },
];

function getBadgeVariant(status: string) {
  switch (status) {
    case "Ready":
      return "default";

    case "Processing":
      return "secondary";

    default:
      return "outline";
  }
}

export default function ReportsTable() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Generated Reports</CardTitle>

        <CardDescription>
          View previously generated reports and prepare them for preview or
          export.
        </CardDescription>
      </CardHeader>

      <CardContent>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Report ID</TableHead>
              <TableHead>Report Name</TableHead>
              <TableHead>Type</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead>Date</TableHead>
              <TableHead>Status</TableHead>
              <TableHead className="text-right">
                Actions
              </TableHead>
            </TableRow>
          </TableHeader>

          <TableBody>
            {reports.map((report) => (
              <TableRow key={report.id}>
                <TableCell className="font-medium">
                  {report.id}
                </TableCell>

                <TableCell>{report.name}</TableCell>

                <TableCell>{report.type}</TableCell>

                <TableCell>{report.generatedBy}</TableCell>

                <TableCell>{report.date}</TableCell>

                <TableCell>
                  <Badge variant={getBadgeVariant(report.status)}>
                    {report.status}
                  </Badge>
                </TableCell>

                <TableCell>
                  <div className="flex justify-end gap-2">
                    <Button
                      variant="outline"
                      size="icon"
                    >
                      <Eye className="h-4 w-4" />
                    </Button>

                    <Button
                      variant="outline"
                      size="icon"
                    >
                      <Download className="h-4 w-4" />
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}